"""Daily report download CLI commands.

This module provides the `aigon report <agent>` command for downloading
existing daily reports from the database to local files.

(c) Stefan LOESCH 2025-26. All rights reserved.
"""

import argparse
import asyncio
import json
import logging
from datetime import datetime, timedelta, time, timezone
from pathlib import Path
from typing import Dict, Any, List, Optional, Tuple


def register_report_commands(subparsers):
    """Register 'aigon report' command with agent subcommands.

    Args:
        subparsers: argparse subparsers object
    """
    report_parser = subparsers.add_parser(
        'report',
        help='Download daily reports from database',
        description='Retrieve existing daily reports generated by scheduler'
    )

    # Agent subparser (notetaker, wellness, coach, diary)
    agent_subparsers = report_parser.add_subparsers(
        dest='agent',
        required=True,
        help='Agent to download reports from'
    )

    # Common arguments for all agents
    for agent_name in ['notetaker', 'wellness', 'coach', 'diary']:
        agent_parser = agent_subparsers.add_parser(
            agent_name,
            help=f'Download {agent_name} daily reports'
        )
        add_common_report_args(agent_parser)

    report_parser.set_defaults(func=handle_report_command)


def add_common_report_args(parser):
    """Add common report arguments to parser.

    Args:
        parser: argparse parser object
    """
    # Report type (default: daily, future: weekly, monthly)
    parser.add_argument(
        '--daily',
        action='store_true',
        default=True,
        help='Download daily reports (default)'
    )

    # Positional argument: number of most recent reports (default: 1)
    parser.add_argument(
        'count',
        nargs='?',
        type=int,
        default=None,
        metavar='N',
        help='Download last N reports (default: 1). Cannot combine with --from/--to/--all.'
    )

    # Time period options (mutually exclusive with count)
    parser.add_argument(
        '--from',
        dest='date_from',
        type=str,
        metavar='DATE',
        help='Start date (YYYY-MM-DD or Unix timestamp)'
    )
    parser.add_argument(
        '--to',
        dest='date_to',
        type=str,
        metavar='DATE',
        help='End date (YYYY-MM-DD or Unix timestamp) - requires --from'
    )
    parser.add_argument(
        '--all',
        action='store_true',
        help='Download all available daily reports'
    )

    # Output options
    parser.add_argument(
        '--output-dir',
        type=str,
        default='.',
        help='Output directory for downloaded reports (default: current directory)'
    )
    parser.add_argument(
        '--format',
        choices=['file', 'json'],
        default='file',
        help='Output format: file (save to disk) or json (print metadata)'
    )
    parser.add_argument(
        '-v', '--verbose',
        action='store_true',
        help='Verbose logging'
    )


def validate_time_args(args) -> None:
    """Validate that count isn't combined with other time options.

    Args:
        args: Parsed command-line arguments

    Raises:
        ValueError: If count is combined with other time options
    """
    has_time_option = args.date_from or args.date_to or args.all

    if args.count is not None and has_time_option:
        raise ValueError(
            "Cannot combine count (N) with other time options (--from, --to, --all). "
            "Use either 'aigon report notetaker 5' OR 'aigon report notetaker --from DATE'"
        )

    if args.date_to and not args.date_from:
        raise ValueError("--to requires --from")


def parse_time_period(args) -> Tuple[Optional[datetime.date], Optional[datetime.date]]:
    """Parse time period arguments to (start_date, end_date) tuple.

    Args:
        args: Parsed command-line arguments

    Returns:
        (start_date, end_date) inclusive range, or (None, None) for count-based or --all

    Raises:
        ValueError: If invalid date format
    """
    # Count-based: no date filtering, handled separately
    if args.count is not None or not (args.date_from or args.all):
        # Return None to indicate "query by count, not date"
        return None, None

    # --from DATE [--to DATE]
    if args.date_from:
        start_date = parse_date(args.date_from)
        end_date = parse_date(args.date_to) if args.date_to else start_date

        if end_date < start_date:
            raise ValueError(f"End date {end_date} is before start date {start_date}")

        return start_date, end_date

    # --all (query for all available)
    if args.all:
        return None, None

    # Shouldn't reach here
    return None, None


def parse_date(date_str: str) -> datetime.date:
    """Parse date string in YYYY-MM-DD or Unix timestamp format.

    Args:
        date_str: Date string to parse

    Returns:
        Parsed date object

    Raises:
        ValueError: If invalid date format
    """
    # Try Unix timestamp first
    try:
        timestamp = int(date_str)
        return datetime.fromtimestamp(timestamp, tz=timezone.utc).date()
    except ValueError:
        pass

    # Try ISO date format
    try:
        return datetime.strptime(date_str, '%Y-%m-%d').date()
    except ValueError:
        raise ValueError(
            f"Invalid date format: {date_str}. "
            "Use YYYY-MM-DD or Unix timestamp."
        )


def query_daily_reports(
    agent_name: str,
    start_date: Optional[datetime.date],
    end_date: Optional[datetime.date],
    client,
    limit: Optional[int] = None
) -> List[Dict[str, Any]]:
    """Query daily reports for date range or by count.

    Args:
        agent_name: 'notetaker', 'wellness', 'coach', or 'diary'
        start_date: Start date (inclusive), or None for count-based/all
        end_date: End date (inclusive), or None for count-based/all
        client: AigonClient instance
        limit: If set, return only the last N reports (ignores date range)

    Returns:
        List of note dicts with attachment metadata
    """

    # Build query parameters - filter by key:value tags
    agent_tag = f"agent:{agent_name}"
    reporttype_tag = "reporttype:daily"

    # Calculate time window for query using absolute timestamps
    # Daily reports have created_at set to 23:59:59 on the report date
    if start_date and end_date:
        # Convert dates to Unix timestamps
        start_ts = int(datetime.combine(
            start_date, time.min, tzinfo=timezone.utc
        ).timestamp())
        end_ts = int(datetime.combine(
            end_date, time.max, tzinfo=timezone.utc
        ).timestamp())
        time_window_start = None  # Use absolute timestamps
    else:
        # All available (or count-based - will filter after)
        start_ts = None
        end_ts = None
        time_window_start = 365 * 10  # 10 years - effectively all time

    # Query notes via API
    # When using date range: use absolute timestamps with time_field='created'
    # When using count: use large time_window_start to get all available
    all_notes = client.get_recent_notes(
        limit=1000,
        start_ts=start_ts,
        end_ts=end_ts,
        time_window_start=time_window_start,
        time_field='created',  # Match on created_at (report date)
        note_type='system',
        processed_status='all',  # Include all notes regardless of processed status
        reverse=True,  # Most recent first
        with_attachments=True,  # Include attachment metadata
        agent_filter=agent_name  # Filter by agent (notetaker, wellness, coach, diary)
    )

    # Filter by tags manually (API doesn't support tag filtering yet)
    notes = [note for note in all_notes
             if agent_tag in note.get('tags', []) and reporttype_tag in note.get('tags', [])]

    # Sort by created_at descending (most recent first)
    notes.sort(key=lambda n: n.get('created_at', 0), reverse=True)

    # Filter to exact date range (query might return extra)
    if start_date and end_date:
        filtered_notes = []
        for note in notes:
            created_dt = datetime.fromtimestamp(note['created_at'], tz=timezone.utc)
            note_date = created_dt.date()
            if start_date <= note_date <= end_date:
                filtered_notes.append(note)
        notes = filtered_notes

    # Apply limit if count-based query
    if limit is not None and limit > 0:
        notes = notes[:limit]

    return notes


def download_attachment(
    attachment_unique_id: str,
    client
) -> bytes:
    """Download attachment content from API.

    Args:
        attachment_unique_id: Attachment unique_id (10 chars)
        client: AigonClient instance

    Returns:
        Binary attachment content
    """
    # Call API endpoint: GET /notetaker/attachments/{unique_id}
    # Returns (content_bytes, mime_type, filename)
    content_bytes, _, _ = client.get_attachment_by_unique_id(attachment_unique_id)

    return content_bytes


def save_report_to_file(
    content: bytes,
    filename: str,
    report_date: datetime.date,
    agent_name: str,
    output_dir: str = '.'
) -> str:
    """Save report content to local file.

    Args:
        content: Binary markdown content
        filename: Original filename from attachment
        report_date: Date of the report
        agent_name: Agent name (notetaker, wellness, etc.)
        output_dir: Output directory path

    Returns:
        Absolute path to saved file
    """
    # Create output directory (if it doesn't exist)
    output_path = Path(output_dir)
    output_path.mkdir(parents=True, exist_ok=True)

    # Use original filename or generate from date
    if not filename:
        filename = f"{report_date.strftime('%Y%m%d')}_{agent_name}_daily.md"

    filepath = output_path / filename

    # Write binary content to file
    with open(filepath, 'wb') as f:
        f.write(content)

    return str(filepath.absolute())


def download_daily_reports(args) -> int:
    """Main function to download daily reports.

    Args:
        args: Parsed command-line arguments

    Returns:
        Exit code (0 = success, 1 = error)
    """
    from .client import AigonClient
    from .config import get_api_url, get_api_token

    # Setup logging - simple format for CLI
    log_level = logging.DEBUG if args.verbose else logging.INFO
    logging.basicConfig(
        level=log_level,
        format='%(message)s'
    )
    logger = logging.getLogger(__name__)

    # Validate arguments
    try:
        validate_time_args(args)
    except ValueError as e:
        logger.error(str(e))
        return 1

    # Initialize API client (user is determined from API token)
    base_url = get_api_url()
    api_token = get_api_token()
    client = AigonClient(base_url=base_url, api_token=api_token)

    # Determine query mode: count-based or date-based
    # Default to count=1 if no options specified
    count = args.count if args.count is not None else 1
    use_count_mode = not (args.date_from or args.all)

    # Parse time period for date-based queries
    try:
        start_date, end_date = parse_time_period(args)
    except ValueError as e:
        logger.error(f"Invalid time period: {e}")
        return 1

    # Log operation
    if use_count_mode:
        logger.info(f"Downloading last {count} {args.agent} daily report(s)")
    elif start_date and end_date:
        if start_date == end_date:
            logger.info(f"Downloading {args.agent} daily report for {start_date}")
        else:
            logger.info(
                f"Downloading {args.agent} daily reports from "
                f"{start_date} to {end_date}"
            )
    else:
        logger.info(f"Downloading all available {args.agent} daily reports")

    # Query for daily reports
    try:
        notes = query_daily_reports(
            agent_name=args.agent,
            start_date=start_date,
            end_date=end_date,
            client=client,
            limit=count if use_count_mode else None
        )
    except Exception as e:
        logger.error(f"Error querying reports: {e}")
        return 1

    if not notes:
        logger.warning("No daily reports found")
        return 0

    logger.info(f"Found {len(notes)} daily report(s)")

    # JSON format - just print metadata
    if args.format == 'json':
        output = []
        for note in notes:
            created_dt = datetime.fromtimestamp(note['created_at'], tz=timezone.utc)
            attachments = note.get('attachments', [])
            if len(attachments) > 1:
                logger.error(f"Report note {note.get('unique_id')} has {len(attachments)} attachments, expected 1")
            attachment_info = attachments[0] if attachments else {}
            # Extract attachment metadata if available
            if attachment_info:
                attachment_metadata = {
                    'unique_id': attachment_info.get('unique_id'),
                    'filename': attachment_info.get('filename'),
                    'file_type': attachment_info.get('file_type'),
                    'mime_type': attachment_info.get('mime_type')
                }
            else:
                attachment_metadata = None

            output.append({
                'date': created_dt.date().isoformat(),
                'note_unique_id': note['unique_id'],
                'attachment': attachment_metadata
            })
        print(json.dumps(output, indent=2))
        return 0

    # File format - download and save
    results = []
    for idx, note in enumerate(notes, 1):
        created_dt = datetime.fromtimestamp(note['created_at'], tz=timezone.utc)
        report_date = created_dt.date()

        logger.info(f"[{idx}/{len(notes)}] Downloading report for {report_date}")

        # Get attachment info
        attachments = note.get('attachments', [])
        if not attachments:
            logger.warning(f"  No attachment found for {report_date}")
            results.append({'date': report_date, 'status': 'no_attachment'})
            continue

        if len(attachments) > 1:
            logger.error(f"Report note {note.get('unique_id')} has {len(attachments)} attachments, expected 1")
        attachment = attachments[0]
        attachment_id = attachment['unique_id']
        filename = attachment.get('filename', '')

        try:
            # Download attachment content
            content = download_attachment(attachment_id, client)

            # Save to file
            filepath = save_report_to_file(
                content=content,
                filename=filename,
                report_date=report_date,
                agent_name=args.agent,
                output_dir=args.output_dir
            )

            logger.info(f"  ✓ Saved to: {filepath}")
            results.append({
                'date': report_date,
                'status': 'success',
                'filepath': filepath
            })

        except Exception as e:
            logger.error(f"  ✗ Error downloading {report_date}: {e}")
            results.append({
                'date': report_date,
                'status': 'error',
                'error': str(e)
            })

    # Print summary
    logger.info("")
    logger.info("=" * 60)
    success_count = sum(1 for r in results if r.get('status') == 'success')
    error_count = sum(1 for r in results if r.get('status') == 'error')
    logger.info(f"SUMMARY: {len(results)} reports processed")
    logger.info(f"  Success: {success_count}")
    logger.info(f"  Errors:  {error_count}")

    return 0 if error_count == 0 else 1


def handle_report_command(args) -> int:
    """Handle 'aigon report' command.

    Args:
        args: Parsed command-line arguments with 'agent' subcommand

    Returns:
        Exit code
    """
    # Run download function (synchronous, not async)
    return download_daily_reports(args)
